@startuml
title Morning Habits [60min]
start
->7AM;
:起床; 
:ダウンに着替える;
:2Fに降りる;
:口を濯いで水を飲む;
if (雨ではない？) then (true)
    :ランニングに行く;
    note left
    お茶菓子
    end note
else (false)
    :スクワットを30回する;
Endif
:紅茶を飲む;
:読書をする;
note right: 紅茶を飲みながら
:歯を磨く;
:出勤;
->8PM;
stop
@enduml